#!/bin/bash
if [[ -x /usr/bin/xbps-install ]]; then
    alias update='sudo xbps-install -Syu && rustup update'
    alias uninstall='sudo xbps-remove'
    alias install='sudo xbps-install -S'
    alias checkupdates='xbps-install -Mun'
elif [[ -x /usr/bin/pacman ]]; then
    alias update='sudo pacman -Syu --noconfirm && rustup update'
    alias uninstall='sudo pacman -Rsn'
    alias install='sudo pacman -S'
elif [[ -x /usr/bin/dpkg ]]; then
    alias update='sudo apt update && sudo apt upgrade && rustup update'
    alias uninstall='sudo apt remove'
    alias install='sudo apt install'
		alias checkupdates="apt-get -s dist-upgrade | awk '/^Inst/ { print $2 }' | wc -l``"
else
    echo "Couldn't find package manager"
fi

if [[ -x /usr/lib/systemd ]]; then
    alias poweroff='sudo systemctl poweroff'
    alias reboot='sudo systemctl reboot'
else
    alias poweroff='sudo loginctl poweroff'
    alias reboot='sudo loginctl reboot'
fi
