#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -theme ~/.config/leftwm/themes/current/rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -10 -yoffset 32 -width 10 -hide-scrollbar -line-padding 4 -padding 10 -lines 8 <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) i3lockr --blur 25 -- --nofork --ignore-empty-password;;
                *Logout) pkill leftwm;;
                *Reboot) systemctl reboot;;
                *Shutdown) systemctl -i poweroff;;
            esac
